version: '3'
services:
  anh_backend:
    build: .
    image: anh-backend:1.1.2
    container_name: anh-backend-1.1.2
    environment:
      - NODE_CONFIG_ENV=production
    volumes:
      - ./config/production.json:/home/node/app/config/production.json
    ports:
      - "4500:4000"
    restart: always
